-- SHM 数据库建表脚本
CREATE DATABASE IF NOT EXISTS shm DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE shm;

-- 用户表
CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  nickname VARCHAR(50),
  role VARCHAR(20) DEFAULT 'user' COMMENT 'admin / user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 菜单表
CREATE TABLE IF NOT EXISTS menus (
  id INT PRIMARY KEY AUTO_INCREMENT,
  menu_id VARCHAR(20) NOT NULL UNIQUE,
  parent_id VARCHAR(20) DEFAULT NULL,
  menu_type TINYINT NOT NULL COMMENT '1=分组, 2=叶子',
  menu_name VARCHAR(100) NOT NULL,
  path VARCHAR(200) DEFAULT NULL,
  sort_order INT DEFAULT 0
);

-- 主机表
CREATE TABLE IF NOT EXISTS hosts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  host_type VARCHAR(20) NOT NULL COMMENT 'AIX / Linux',
  host_name VARCHAR(100) NOT NULL,
  ip_address VARCHAR(50) NOT NULL,
  description VARCHAR(200),
  status_info VARCHAR(20) DEFAULT 'Health' COMMENT 'Health / Warning / Severe',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- CPU 性能数据表
CREATE TABLE IF NOT EXISTS cpu_performance (
  id INT PRIMARY KEY AUTO_INCREMENT,
  host_id INT,
  metric_name VARCHAR(20) NOT NULL COMMENT 'user/sys/idle/iowait/entc',
  metric_date DATE NOT NULL,
  hour_0 DOUBLE DEFAULT 0,
  hour_1 DOUBLE DEFAULT 0,
  hour_2 DOUBLE DEFAULT 0,
  hour_3 DOUBLE DEFAULT 0,
  hour_4 DOUBLE DEFAULT 0,
  hour_5 DOUBLE DEFAULT 0,
  hour_6 DOUBLE DEFAULT 0,
  hour_7 DOUBLE DEFAULT 0,
  hour_8 DOUBLE DEFAULT 0,
  hour_9 DOUBLE DEFAULT 0,
  hour_10 DOUBLE DEFAULT 0,
  hour_11 DOUBLE DEFAULT 0,
  hour_12 DOUBLE DEFAULT 0,
  hour_13 DOUBLE DEFAULT 0,
  hour_14 DOUBLE DEFAULT 0,
  hour_15 DOUBLE DEFAULT 0,
  hour_16 DOUBLE DEFAULT 0,
  hour_17 DOUBLE DEFAULT 0,
  hour_18 DOUBLE DEFAULT 0,
  hour_19 DOUBLE DEFAULT 0,
  hour_20 DOUBLE DEFAULT 0,
  hour_21 DOUBLE DEFAULT 0,
  hour_22 DOUBLE DEFAULT 0,
  hour_23 DOUBLE DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (host_id) REFERENCES hosts(id) ON DELETE SET NULL
);
