const { execCommand } = require('./sshService');

/**
 * Linux 巡检脚本内容（展示用）
 */
const INSPECTION_SCRIPT = `#!/bin/bash
# SHM Linux Health Check Script
# Generated by SHM System Health Management

echo "===== System Information ====="
echo "--- OS Version ---"
cat /etc/os-release 2>/dev/null | grep PRETTY_NAME | cut -d= -f2 | tr -d '"'
echo "--- Kernel ---"
uname -r
echo "--- Architecture ---"
uname -m
echo "--- Hostname ---"
hostname
echo "--- Uptime ---"
uptime -p 2>/dev/null || uptime
echo "--- Load Average ---"
cat /proc/loadavg

echo ""
echo "===== CPU Information ====="
echo "--- CPU Cores ---"
nproc
echo "--- CPU Usage (top) ---"
top -bn1 | head -5

echo ""
echo "===== Memory Information ====="
free -m

echo ""
echo "===== Disk Information ====="
df -h

echo ""
echo "===== Network Information ====="
ip -br addr 2>/dev/null || ifconfig 2>/dev/null
echo "--- Network Traffic ---"
cat /proc/net/dev

echo ""
echo "===== Filesystem Check ====="
echo "--- Filesystems over 80% usage ---"
df -h | awk 'NR>1 && +\$5 > 80 {print \$0}'

echo ""
echo "===== System Errors ====="
echo "--- Recent errors (last 50 lines) ---"
journalctl -p err --no-pager -n 50 2>/dev/null || tail -50 /var/log/messages 2>/dev/null

echo ""
echo "===== Top Processes ====="
ps aux --sort=-%mem | head -11

echo ""
echo "===== SELinux Status ====="
getenforce 2>/dev/null || echo "N/A"

echo ""
echo "===== Firewall Status ====="
systemctl is-active firewalld 2>/dev/null || echo "N/A"

echo ""
echo "===== Last Reboot ---"
last reboot | head -3

echo ""
echo "===== Check Complete ====="`;

/**
 * 通过 SSH 执行 Linux 巡检
 */
async function runInspection(host, port, user, password) {
  const [
    osRaw, kernelRaw, archRaw, hostnameRaw, uptimeRaw, loadRaw,
    coresRaw, cpuRaw,
    memRaw,
    diskRaw,
    netAddrRaw, netDevRaw,
    fsOver80Raw,
    errorsRaw,
    topProcRaw,
    selinuxRaw,
    firewallRaw,
    rebootRaw
  ] = await Promise.all([
    execCommand(host, port, user, password, 'cat /etc/os-release 2>/dev/null | grep PRETTY_NAME | cut -d= -f2 | tr -d \\"'),
    execCommand(host, port, user, password, 'uname -r'),
    execCommand(host, port, user, password, 'uname -m'),
    execCommand(host, port, user, password, 'hostname'),
    execCommand(host, port, user, password, 'uptime -p 2>/dev/null || uptime'),
    execCommand(host, port, user, password, 'cat /proc/loadavg'),
    execCommand(host, port, user, password, 'nproc'),
    execCommand(host, port, user, password, 'top -bn1 | head -5'),
    execCommand(host, port, user, password, 'free -m'),
    execCommand(host, port, user, password, 'df -h'),
    execCommand(host, port, user, password, 'ip -br addr 2>/dev/null || ifconfig 2>/dev/null'),
    execCommand(host, port, user, password, 'cat /proc/net/dev'),
    execCommand(host, port, user, password, "df -h | awk 'NR>1 && +$5 > 80 {print $0}'"),
    execCommand(host, port, user, password, 'journalctl -p err --no-pager -n 50 2>/dev/null || tail -50 /var/log/messages 2>/dev/null'),
    execCommand(host, port, user, password, 'ps aux --sort=-%mem | head -11'),
    execCommand(host, port, user, password, 'getenforce 2>/dev/null || echo N/A'),
    execCommand(host, port, user, password, 'systemctl is-active firewalld 2>/dev/null || echo N/A'),
    execCommand(host, port, user, password, 'last reboot | head -3')
  ]);

  // 解析内存
  const memLines = memRaw.trim().split('\n');
  const memParts = (memLines.find(l => l.startsWith('Mem:')) || '').trim().split(/\s+/);
  const swapParts = (memLines.find(l => l.startsWith('Swap:')) || '').trim().split(/\s+/);

  // 解析 CPU
  const cpuLine = cpuRaw.split('\n').find(l => l.includes('%Cpu') || l.includes('Cpu(s)')) || '';
  const cpuGet = (label) => { const m = cpuLine.match(new RegExp(`(\\d+\\.?\\d*)\\s*${label}`)); return m ? parseFloat(m[1]) : 0; };

  // 解析磁盘
  const diskLines = diskRaw.trim().split('\n').slice(1).filter(l => l.trim());
  const disks = diskLines.map(l => {
    const p = l.trim().split(/\s+/);
    return { filesystem: p[0], size: p[1], used: p[2], avail: p[3], usePercent: p[4], mount: p[5] };
  });

  // 解析 top 进程
  const procLines = topProcRaw.trim().split('\n').slice(1).filter(l => l.trim());
  const processes = procLines.map(l => {
    const p = l.trim().split(/\s+/);
    return { user: p[0], pid: p[1], cpu: p[2], mem: p[3], command: p.slice(10).join(' ') };
  });

  return {
    systemInfo: {
      osVersion: osRaw.trim(),
      kernel: kernelRaw.trim(),
      architecture: archRaw.trim(),
      hostname: hostnameRaw.trim(),
      uptime: uptimeRaw.trim(),
      loadAvg: loadRaw.trim(),
      cpuCores: parseInt(coresRaw.trim()) || 0,
      selinux: selinuxRaw.trim(),
      firewall: firewallRaw.trim()
    },
    cpu: {
      user: cpuGet('us'), system: cpuGet('sy'), idle: cpuGet('id'), iowait: cpuGet('wa')
    },
    memory: {
      total: parseInt(memParts[1]) || 0,
      used: parseInt(memParts[2]) || 0,
      free: parseInt(memParts[3]) || 0,
      swapTotal: parseInt(swapParts[1]) || 0,
      swapUsed: parseInt(swapParts[2]) || 0
    },
    disks,
    filesystemOver80: fsOver80Raw.trim(),
    errors: errorsRaw.trim(),
    processes,
    reboot: rebootRaw.trim(),
    networkAddr: netAddrRaw.trim()
  };
}

module.exports = { INSPECTION_SCRIPT, runInspection };
