const { execCommands } = require('./sshService');

/**
 * Linux RHEL8 巡检脚本
 */
const LINUX_SCRIPT_NAME = 'Linux_RHEL8.sh';

const LINUX_INSPECTION_SCRIPT = `#!/bin/bash
# SHM Linux Health Check Script
# Generated by SHM System Health Management

echo "===== System Information ====="
echo "--- OS Version ---"
cat /etc/os-release 2>/dev/null | grep PRETTY_NAME | cut -d= -f2 | tr -d '"'
echo "--- Kernel ---"
uname -r
echo "--- Architecture ---"
uname -m
echo "--- Hostname ---"
hostname
echo "--- Uptime ---"
uptime -p 2>/dev/null || uptime
echo "--- Load Average ---"
cat /proc/loadavg

echo ""
echo "===== CPU Information ====="
echo "--- CPU Cores ---"
nproc
echo "--- CPU Usage (top) ---"
top -bn1 | head -5

echo ""
echo "===== Memory Information ====="
free -m

echo ""
echo "===== Disk Information ====="
df -h

echo ""
echo "===== Network Information ====="
ip -br addr 2>/dev/null || ifconfig 2>/dev/null
echo "--- Network Traffic ---"
cat /proc/net/dev

echo ""
echo "===== Filesystem Check ====="
echo "--- Filesystems over 80% usage ---"
df -h | awk 'NR>1 && +$5 > 80 {print $0}'

echo ""
echo "===== System Errors ====="
echo "--- Recent errors (last 50 lines) ---"
journalctl -p err --no-pager -n 50 2>/dev/null || tail -50 /var/log/messages 2>/dev/null

echo ""
echo "===== Top Processes ====="
ps aux --sort=-%mem | head -11

echo ""
echo "===== SELinux Status ====="
getenforce 2>/dev/null || echo N/A

echo ""
echo "===== Firewall Status ====="
systemctl is-active firewalld 2>/dev/null || echo N/A

echo ""
echo "===== Last Reboot ---"
last reboot | head -3

echo ""
echo "===== Check Complete ====="`;

/**
 * AIX 巡检脚本
 */
const AIX_SCRIPT_NAME = 'AIX_Inspection.sh';

const AIX_INSPECTION_SCRIPT = `#!/bin/ksh
# SHM AIX Health Check Script
# Generated by SHM System Health Management

echo "===== System Information ====="
echo "--- OS Version ---"
oslevel -s 2>/dev/null || oslevel 2>/dev/null
echo "--- Kernel ---"
oslevel 2>/dev/null
echo "--- Architecture ---"
uname -m
echo "--- Hostname ---"
hostname
echo "--- Uptime ---"
uptime
echo "--- System Configuration ---"
lsconf 2>/dev/null | head -15

echo ""
echo "===== CPU Information ====="
echo "--- CPU Information ---"
lsdev -Cc processor 2>/dev/null
echo "--- CPU Usage (vmstat) ---"
vmstat 1 3

echo ""
echo "===== Memory Information ====="
echo "--- Memory (svmon) ---"
svmon -G -O unit=MB 2>/dev/null || vmstat -v
echo "--- Paging Space ---"
lsps -a 2>/dev/null

echo ""
echo "===== Disk Information ====="
df -g

echo ""
echo "===== Network Information ====="
echo "--- Network Interfaces ---"
netstat -i 2>/dev/null
echo "--- IP Configuration ---"
ifconfig -a 2>/dev/null

echo ""
echo "===== Filesystem Check ====="
echo "--- Filesystems over 80% usage ---"
df -g | awk 'NR>1 && +$4 > 80 {print $0}'

echo ""
echo "===== System Errors ====="
echo "--- Error Report (last 50 entries) ---"
errpt -a 2>/dev/null | head -100

echo ""
echo "===== Top Processes ====="
ps aux 2>/dev/null | head -11 || ps -ef | head -11

echo ""
echo "===== LPAR Information ====="
lparstat 2>/dev/null | head -10

echo ""
echo "===== IO Statistics ====="
iostat 2>/dev/null | head -10

echo ""
echo "===== Filesystem Mounts ====="
mount | grep -v NFS

echo ""
echo "===== Last Reboot ---"
last reboot | head -3

echo ""
echo "===== Check Complete ====="`;

/**
 * 根据系统类型获取巡检脚本配置
 */
function getInspectionConfig(hostType) {
  if (hostType === 'AIX') {
    return {
      scriptName: AIX_SCRIPT_NAME,
      script: AIX_INSPECTION_SCRIPT,
      runInspection: runAIXInspection
    };
  }
  // 默认 Linux
  return {
    scriptName: LINUX_SCRIPT_NAME,
    script: LINUX_INSPECTION_SCRIPT,
    runInspection: runLinuxInspection
  };
}

/**
 * Linux 巡检命令执行
 */
async function runLinuxInspection(host, port, user, password) {
  const cmds = [
    'cat /etc/os-release 2>/dev/null | grep PRETTY_NAME | cut -d= -f2 | tr -d \\"',  // 0
    'uname -r',                                                                        // 1
    'uname -m',                                                                        // 2
    'hostname',                                                                        // 3
    'uptime -p 2>/dev/null || uptime',                                                 // 4
    'cat /proc/loadavg',                                                               // 5
    'nproc',                                                                           // 6
    'top -bn1 | head -5',                                                              // 7
    'free -m',                                                                         // 8
    'df -h',                                                                           // 9
    'ip -br addr 2>/dev/null || ifconfig 2>/dev/null',                                 // 10
    'cat /proc/net/dev',                                                               // 11
    "df -h | awk 'NR>1 && +$5 > 80 {print $0}'",                                      // 12
    'journalctl -p err --no-pager -n 50 2>/dev/null || tail -50 /var/log/messages 2>/dev/null', // 13
    'ps aux --sort=-%mem | head -11',                                                  // 14
    'getenforce 2>/dev/null || echo N/A',                                              // 15
    'systemctl is-active firewalld 2>/dev/null || echo N/A',                           // 16
    'last reboot | head -3'                                                            // 17
  ];

  const results = await execCommands(host, port, user, password, cmds);

  const [
    osRaw, kernelRaw, archRaw, hostnameRaw, uptimeRaw, loadRaw,
    coresRaw, cpuRaw,
    memRaw,
    diskRaw,
    netAddrRaw, netDevRaw,
    fsOver80Raw,
    errorsRaw,
    topProcRaw,
    selinuxRaw,
    firewallRaw,
    rebootRaw
  ] = results;

  // 解析内存
  const memLines = memRaw.trim().split('\n');
  const memParts = (memLines.find(l => l.startsWith('Mem:')) || '').trim().split(/\s+/);
  const swapParts = (memLines.find(l => l.startsWith('Swap:')) || '').trim().split(/\s+/);

  // 解析 CPU
  const cpuLine = cpuRaw.split('\n').find(l => l.includes('%Cpu') || l.includes('Cpu(s)')) || '';
  const cpuGet = (label) => { const m = cpuLine.match(new RegExp(`(\\d+\\.?\\d*)\\s*${label}`)); return m ? parseFloat(m[1]) : 0; };

  // 解析磁盘
  const diskLines = diskRaw.trim().split('\n').slice(1).filter(l => l.trim());
  const disks = diskLines.map(l => {
    const p = l.trim().split(/\s+/);
    return { filesystem: p[0], size: p[1], used: p[2], avail: p[3], usePercent: p[4], mount: p[5] };
  });

  // 解析 top 进程
  const procLines = topProcRaw.trim().split('\n').slice(1).filter(l => l.trim());
  const processes = procLines.map(l => {
    const p = l.trim().split(/\s+/);
    return { user: p[0], pid: p[1], cpu: p[2], mem: p[3], command: p.slice(10).join(' ') };
  });

  return {
    systemInfo: {
      osVersion: osRaw.trim(),
      kernel: kernelRaw.trim(),
      architecture: archRaw.trim(),
      hostname: hostnameRaw.trim(),
      uptime: uptimeRaw.trim(),
      loadAvg: loadRaw.trim(),
      cpuCores: parseInt(coresRaw.trim()) || 0,
      selinux: selinuxRaw.trim(),
      firewall: firewallRaw.trim()
    },
    cpu: {
      user: cpuGet('us'), system: cpuGet('sy'), idle: cpuGet('id'), iowait: cpuGet('wa')
    },
    memory: {
      total: parseInt(memParts[1]) || 0,
      used: parseInt(memParts[2]) || 0,
      free: parseInt(memParts[3]) || 0,
      swapTotal: parseInt(swapParts[1]) || 0,
      swapUsed: parseInt(swapParts[2]) || 0
    },
    disks,
    filesystemOver80: fsOver80Raw.trim(),
    errors: errorsRaw.trim(),
    processes,
    reboot: rebootRaw.trim(),
    networkAddr: netAddrRaw.trim()
  };
}

/**
 * AIX 巡检命令执行
 */
async function runAIXInspection(host, port, user, password) {
  const cmds = [
    'oslevel -s 2>/dev/null || oslevel 2>/dev/null',            // 0 - OS version
    'oslevel 2>/dev/null',                                       // 1 - Kernel
    'uname -m',                                                  // 2 - Architecture
    'hostname',                                                  // 3 - Hostname
    'uptime',                                                    // 4 - Uptime
    'lsconf 2>/dev/null | head -15',                             // 5 - System config
    'lsdev -Cc processor 2>/dev/null',                           // 6 - CPU info
    'vmstat 1 3',                                                // 7 - CPU usage
    'svmon -G -O unit=MB 2>/dev/null || vmstat -v',             // 8 - Memory
    'lsps -a 2>/dev/null',                                       // 9 - Paging space
    'df -g',                                                     // 10 - Disk
    'netstat -i 2>/dev/null',                                    // 11 - Network
    'ifconfig -a 2>/dev/null',                                   // 12 - IP config
    "df -g | awk 'NR>1 && +$4 > 80 {print $0}'",                // 13 - Filesystem over 80%
    'errpt -a 2>/dev/null | head -100',                          // 14 - Error report
    'ps aux 2>/dev/null | head -11 || ps -ef | head -11',       // 15 - Top processes
    'lparstat 2>/dev/null | head -10',                           // 16 - LPAR info
    'iostat 2>/dev/null | head -10',                             // 17 - IO stats
    'mount | grep -v NFS',                                       // 18 - Filesystem mounts
    'last reboot | head -3'                                      // 19 - Last reboot
  ];

  const results = await execCommands(host, port, user, password, cmds);

  const [
    osRaw, kernelRaw, archRaw, hostnameRaw, uptimeRaw, configRaw,
    cpuInfoRaw, cpuUsageRaw,
    memRaw, pagingRaw,
    diskRaw,
    netStatRaw, ifconfigRaw,
    fsOver80Raw,
    errorsRaw,
    topProcRaw,
    lparRaw, ioRaw,
    mountsRaw,
    rebootRaw
  ] = results;

  // Parse memory from svmon
  let memTotal = 0, memUsed = 0, memFree = 0;
  const memLines = memRaw.trim().split('\n');
  for (const line of memLines) {
    if (line.includes('unit') || line.includes('------') || line.trim() === '') continue;
    const parts = line.trim().split(/\s+/);
    if (parts.length >= 4 && parts[0] !== 'total' && !isNaN(parseInt(parts[1]))) {
      memTotal += parseInt(parts[1]) || 0;
      memUsed += parseInt(parts[2]) || 0;
    }
  }
  if (memTotal > 0) memFree = memTotal - memUsed;

  // Parse disk from df -g
  const diskLines = diskRaw.trim().split('\n').slice(1);
  const disks = diskLines.filter(l => l.trim()).map(l => {
    const p = l.trim().split(/\s+/);
    if (p.length < 7) return null;
    return { filesystem: p[0], size: p[1] + 'G', used: p[2] + 'G', avail: p[3] + 'G', usePercent: parseInt(p[4]) || 0, mount: p[6] };
  }).filter(Boolean);

  // Parse top processes
  const procLines = topProcRaw.trim().split('\n').slice(1);
  const processes = procLines.filter(l => l.trim()).map(l => {
    const p = l.trim().split(/\s+/);
    if (p.length < 11) return null;
    return { user: p[0], pid: p[1], cpu: p[2], mem: p[3], command: p.slice(10).join(' ') };
  }).filter(Boolean);

  // Parse load average from uptime
  const loadMatch = uptimeRaw.match(/load average:\s*([\d.]+)\s*([\d.]+)\s*([\d.]+)/);
  const loadAvg = {
    '1min': loadMatch ? parseFloat(loadMatch[1]) : 0,
    '5min': loadMatch ? parseFloat(loadMatch[2]) : 0,
    '15min': loadMatch ? parseFloat(loadMatch[3]) : 0
  };

  return {
    systemInfo: {
      osVersion: osRaw.trim() || 'AIX',
      kernel: kernelRaw.trim(),
      architecture: archRaw.trim(),
      hostname: hostnameRaw.trim(),
      uptime: uptimeRaw.trim(),
      loadAvg: loadAvg,
      cpuCores: 0,
      selinux: 'N/A',
      firewall: 'N/A',
      lpar: lparRaw.trim(),
      ioStats: ioRaw.trim(),
      config: configRaw.trim(),
      pagingSpace: pagingRaw.trim()
    },
    cpu: {
      user: 0, system: 0, idle: 100, iowait: 0
    },
    memory: {
      total: memTotal,
      used: memUsed,
      free: memFree,
      swapTotal: 0,
      swapUsed: 0
    },
    disks,
    filesystemOver80: fsOver80Raw.trim(),
    errors: errorsRaw.trim(),
    processes,
    reboot: rebootRaw.trim(),
    networkAddr: ifconfigRaw.trim()
  };
}

/**
 * 通过单个 SSH 连接执行所有巡检命令（保持向后兼容）
 */
async function runInspection(host, port, user, password, hostType) {
  if (hostType === 'AIX') {
    return runAIXInspection(host, port, user, password);
  }
  return runLinuxInspection(host, port, user, password);
}

module.exports = {
  LINUX_SCRIPT_NAME, LINUX_INSPECTION_SCRIPT,
  AIX_SCRIPT_NAME, AIX_INSPECTION_SCRIPT,
  getInspectionConfig,
  runInspection, runLinuxInspection, runAIXInspection
};
